name: Coffee-cart testing workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker-action@v4.3.0

      - name: Build Docker image
        run: docker build -t e2e-tests .

      - name: Run e2e tests
        run: |
          docker run -v $PWD/allure_results:/allure_results e2e-tests

      - name: Upload Allure Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure_results
          path: allure_results
