name: Playwright Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker:19.03.12
      options: --privileged

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run Playwright tests
        run: docker run  -v /tmp/allure-results:/allure-results playwright-tests

      - name: Set up Allure Report
        uses: allure-framework/allure-action@v3
        with:
          allure_version: '2.13.8' # Specify the Allure version

      - name: Generate Allure Report
        run: allure generate --clean /tmp/allure-results --output allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/
