name: Playwright Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run Playwright tests
        run: |
          mkdir -p allure-report; 
          docker run  -v $PWD/allure-report:/allure-report playwright-tests;
          echo Execution complete;
          ls $PWD/allure-report;

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allurereport
